### ISSUE TITLE
I can't see uploaded repositories in portal

### ISSUE THREAD

**Issue by astriker** [goharbor/harbor#10848]
As you see in capture image, I can't see uploaded repositories in portal.
I uploaded a repo in A PC and I even can download the repo in B PC.
How can I resolve this situation?

Centos version: 7.7.1908
docker version: 19.03.6
harbor verion: 1.10.1

![harbor_1_10_1_in_centos7](https://user-images.githubusercontent.com/3645530/75304664-36b6cb80-5887-11ea-9633-dcb99b8c9570.png)

**Comment by ninjadq** [comment]
could you provide your log files?

**Comment by astriker** [comment]
Could you tell me your email?
I'll send to your email.

I keep searching and this issue might be occured by SELinux security context relate with command "chcon" .


> could you provide your log files?

**Comment by bolrock** [comment]
Same problem here.
Ubuntu 18.04
Dcoker 19.03.6
Harbor 1.10.1
Installed from harbor-online-installer-v1.10.1.tgz
The only errors I see in the log is

```
Feb 26 10:47:59 172.28.0.1 registry[1102]: time="2020-02-26T10:47:59.006388078Z" level=error msg="retryingsink: error writing events: httpSink{http://core:8080/service/notifications}: response status 404 Not Found unaccepted, retrying" 
Feb 26 10:47:59 172.28.0.1 registry[1102]: time="2020-02-26T10:47:59.006417145Z" level=warning msg="httpSink{http://core:8080/service/notifications} encountered too many errors, backing off" 
Feb 26 10:48:00 172.28.0.1 registry[1102]: time="2020-02-26T10:48:00.031751466Z" level=error msg="retryingsink: error writing events: httpSink{http://core:8080/service/notifications}: response status 404 Not Found unaccepted, retrying" 
Feb 26 10:48:00 172.28.0.1 registry[1102]: time="2020-02-26T10:48:00.031788545Z" level=warning msg="httpSink{http://core:8080/service/notifications} encountered too many errors, backing off" 

```

In my harbor.yml I only changed my hostname and commented all https section.

**Comment by astriker** [comment]
this is all logs after deleting /var/log/harbor/*.log

core.log
===
Feb 27 08:25:17 172.18.0.1 core[21482]: 2020-02-26T23:25:17Z [ERROR] [/common/config/manager.go:118]: loadSystemConfigFromEnv failed, config item, key: clair_db_port,  err: strconv.Atoi: parsing "": invalid syntax
Feb 27 08:25:17 172.18.0.1 core[21482]: 2020-02-26T23:25:17Z [INFO] [/replication/adapter/native/adapter.go:42]: the factory for adapter docker-registry registered
Feb 27 08:25:17 172.18.0.1 core[21482]: 2020-02-26T23:25:17Z [INFO] [/replication/adapter/harbor/adapter.go:40]: the factory for adapter harbor registered
Feb 27 08:25:17 172.18.0.1 core[21482]: 2020-02-26T23:25:17Z [INFO] [/replication/adapter/dockerhub/adapter.go:25]: Factory for adapter docker-hub registered
Feb 27 08:25:17 172.18.0.1 core[21482]: 2020-02-26T23:25:17Z [INFO] [/replication/adapter/huawei/huawei_adapter.go:27]: the factory of Huawei adapter was registered
Feb 27 08:25:17 172.18.0.1 core[21482]: 2020-02-26T23:25:17Z [INFO] [/replication/adapter/googlegcr/adapter.go:29]: the factory for adapter google-gcr registered
Feb 27 08:25:17 172.18.0.1 core[21482]: 2020-02-26T23:25:17Z [INFO] [/replication/adapter/awsecr/adapter.go:47]: the factory for adapter aws-ecr registered
Feb 27 08:25:17 172.18.0.1 core[21482]: 2020-02-26T23:25:17Z [INFO] [/replication/adapter/azurecr/adapter.go:15]: Factory for adapter azure-acr registered
Feb 27 08:25:17 172.18.0.1 core[21482]: 2020-02-26T23:25:17Z [INFO] [/replication/adapter/aliacr/adapter.go:26]: the factory for adapter ali-acr registered
Feb 27 08:25:17 172.18.0.1 core[21482]: 2020-02-26T23:25:17Z [INFO] [/replication/adapter/jfrog/adapter.go:30]: the factory of jfrog artifactory adapter was registered
Feb 27 08:25:17 172.18.0.1 core[21482]: 2020-02-26T23:25:17Z [INFO] [/replication/adapter/quayio/adapter.go:34]: the factory of Quay.io adapter was registered
Feb 27 08:25:17 172.18.0.1 core[21482]: 2020-02-26T23:25:17Z [INFO] [/replication/adapter/helmhub/adapter.go:30]: the factory for adapter helm-hub registered
Feb 27 08:25:17 172.18.0.1 core[21482]: 2020-02-26T23:25:17Z [INFO] [/replication/adapter/gitlab/adapter.go:19]: the factory for adapter gitlab registered
Feb 27 08:25:17 172.18.0.1 core[21482]: 2020-02-26T23:25:17Z [INFO] [/core/controllers/base.go:289]: Config path: /etc/core/app.conf
Feb 27 08:25:17 172.18.0.1 core[21482]: 2020-02-26T23:25:17Z [INFO] [/core/main.go:177]: initializing configurations...
Feb 27 08:25:17 172.18.0.1 core[21482]: 2020-02-26T23:25:17Z [INFO] [/core/config/config.go:100]: key path: /etc/core/key
Feb 27 08:25:17 172.18.0.1 core[21482]: 2020-02-26T23:25:17Z [ERROR] [/common/config/manager.go:118]: loadSystemConfigFromEnv failed, config item, key: clair_db_port,  err: strconv.Atoi: parsing "": invalid syntax
Feb 27 08:25:17 172.18.0.1 core[21482]: 2020-02-26T23:25:17Z [INFO] [/core/config/config.go:73]: init secret store
Feb 27 08:25:17 172.18.0.1 core[21482]: 2020-02-26T23:25:17Z [INFO] [/core/config/config.go:76]: init project manager based on deploy mode
Feb 27 08:25:17 172.18.0.1 core[21482]: 2020-02-26T23:25:17Z [INFO] [/core/config/config.go:145]: initializing the project manager based on local database...
Feb 27 08:25:17 172.18.0.1 core[21482]: 2020-02-26T23:25:17Z [INFO] [/core/main.go:181]: configurations initialization completed
Feb 27 08:25:17 172.18.0.1 core[21482]: 2020-02-26T23:25:17Z [INFO] [/common/dao/base.go:84]: Registering database: type-PostgreSQL host-postgresql port-5432 databse-registry sslmode-"disable"
Feb 27 08:25:17 172.18.0.1 core[21482]: 2020-02-26T23:25:17Z [INFO] [/common/dao/base.go:89]: Register database completed
Feb 27 08:25:17 172.18.0.1 core[21482]: 2020-02-26T23:25:17Z [INFO] [/common/dao/pgsql.go:119]: Upgrading schema for pgsql ...
Feb 27 08:25:17 172.18.0.1 core[21482]: 2020-02-26T23:25:17Z [INFO] [/common/dao/pgsql.go:122]: No change in schema, skip.
Feb 27 08:25:17 172.18.0.1 core[21482]: 2020-02-26T23:25:17Z [INFO] [/core/main.go:83]: User id: 1 already has its encrypted password.
Feb 27 08:25:17 172.18.0.1 core[21482]: 2020-02-26T23:25:17Z [INFO] [/core/main.go:245]: initializing notification...
Feb 27 08:25:17 172.18.0.1 core[21482]: 2020-02-26T23:25:17Z [INFO] [/pkg/notification/notification.go:50]: notification initialization completed
Feb 27 08:25:17 172.18.0.1 core[21482]: 2020-02-26T23:25:17Z [INFO] [/core/main.go:269]: Because SYNC_REGISTRY set false , no need to sync registry 
Feb 27 08:25:17 172.18.0.1 core[21482]: 2020-02-26T23:25:17Z [INFO] [/core/main.go:272]: Init proxy
Feb 27 08:25:17 172.18.0.1 core[21482]: 2020-02-26T23:25:17Z [INFO] [/core/main.go:291]: Version: v1.10.1, Git commit: f3e11715
Feb 27 08:25:17 172.18.0.1 core[21482]: 2020/02/26 23:25:17.795 #033[1;34m[I]#033[0m [asm_amd64.s:1337]  http server Running on http://:8080
Feb 27 08:25:18 172.18.0.1 core[21482]: 2020/02/26 23:25:18.195 #033[1;44m[D]#033[0m [server.go:2774]  |     172.18.0.9|#033[97;42m 200 #033[0m|    1.49646ms|   match|#033[97;44m GET     #033[0m /api/internal/configurations   r:/api/internal/configurations
Feb 27 08:25:47 172.18.0.1 core[21482]: 2020/02/26 23:25:47.823 #033[1;44m[D]#033[0m [server.go:2774]  |      127.0.0.1|#033[97;42m 200 #033[0m|    461.167µs|   match|#033[97;44m GET     #033[0m /api/ping   r:/api/ping
Feb 27 08:25:51 172.18.0.1 core[21482]: 2020/02/26 23:25:51.031 #033[1;44m[D]#033[0m [server.go:2774]  |  160.61.161.93|#033[97;42m 200 #033[0m|   2.578586ms|   match|#033[97;44m GET     #033[0m /api/systeminfo   r:/api/systeminfo
Feb 27 08:25:51 172.18.0.1 core[21482]: 2020-02-26T23:25:51Z [ERROR] [/common/api/base.go:73]: GET /api/users/current failed with error: {"code":401,"message":"UnAuthorize"}
Feb 27 08:25:51 172.18.0.1 core[21482]: 2020/02/26 23:25:51.046 #033[1;44m[D]#033[0m [server.go:2774]  |  160.61.161.93|#033[97;43m 401 #033[0m|   1.885451ms|   match|#033[97;44m GET     #033[0m /api/users/current   r:/api/users/:id
Feb 27 08:25:51 172.18.0.1 core[21482]: 2020-02-26T23:25:51Z [ERROR] [/common/api/base.go:73]: GET /api/users/current failed with error: {"code":401,"message":"UnAuthorize"}
Feb 27 08:25:51 172.18.0.1 core[21482]: 2020/02/26 23:25:51.068 #033[1;44m[D]#033[0m [server.go:2774]  |  160.61.161.93|#033[97;43m 401 #033[0m|   2.077829ms|   match|#033[97;44m GET     #033[0m /api/users/current   r:/api/users/:id
Feb 27 08:25:51 172.18.0.1 core[21482]: 2020/02/26 23:25:51.117 #033[1;44m[D]#033[0m [server.go:2774]  |  160.61.161.93|#033[97;42m 200 #033[0m|   4.422382ms|   match|#033[97;44m GET     #033[0m /api/systeminfo   r:/api/systeminfo
Feb 27 08:25:58 172.18.0.1 core[21482]: 2020/02/26 23:25:58.642 #033[1;44m[D]#033[0m [server.go:2774]  |  160.61.161.93|#033[97;42m 200 #033[0m|  16.225985ms|   match|#033[97;46m POST    #033[0m /c/login   r:/c/login
Feb 27 08:25:58 172.18.0.1 core[21482]: 2020/02/26 23:25:58.676 #033[1;44m[D]#033[0m [server.go:2774]  |  160.61.161.93|#033[97;42m 200 #033[0m|   1.814956ms|   match|#033[97;44m GET     #033[0m /api/users/current   r:/api/users/:id
Feb 27 08:25:58 172.18.0.1 core[21482]: 2020/02/26 23:25:58.742 #033[1;44m[D]#033[0m [server.go:2774]  |  160.61.161.93|#033[97;42m 200 #033[0m|   6.471387ms|   match|#033[97;44m GET     #033[0m /api/scanners   r:/api/scanners
Feb 27 08:25:58 172.18.0.1 core[21482]: 2020/02/26 23:25:58.755 #033[1;44m[D]#033[0m [server.go:2774]  |  160.61.161.93|#033[97;42m 200 #033[0m|   5.487677ms|   match|#033[97;44m GET     #033[0m /api/configurations   r:/api/configurations
Feb 27 08:25:58 172.18.0.1 core[21482]: 2020/02/26 23:25:58.780 #033[1;44m[D]#033[0m [server.go:2774]  |  160.61.161.93|#033[97;42m 200 #033[0m|   3.517916ms|   match|#033[97;44m GET     #033[0m /api/systeminfo/volumes   r:/api/systeminfo/volumes
Feb 27 08:25:58 172.18.0.1 core[21482]: 2020/02/26 23:25:58.789 #033[1;44m[D]#033[0m [server.go:2774]  |  160.61.161.93|#033[97;42m 200 #033[0m|   25.80646ms|   match|#033[97;44m GET     #033[0m /api/statistics   r:/api/statistics
Feb 27 08:25:58 172.18.0.1 core[21482]: 2020/02/26 23:25:58.826 #033[1;44m[D]#033[0m [server.go:2774]  |  160.61.161.93|#033[97;42m 200 #033[0m|  34.803458ms|   match|#033[97;44m GET     #033[0m /api/projects   r:/api/projects/
Feb 27 08:26:01 172.18.0.1 core[21482]: 2020/02/26 23:26:01.287 #033[1;44m[D]#033[0m [server.go:2774]  |  160.61.161.93|#033[97;42m 200 #033[0m|   20.20921ms|   match|#033[97;44m GET     #033[0m /api/projects/2   r:/api/projects/:id([0-9]+)
Feb 27 08:26:01 172.18.0.1 core[21482]: 2020/02/26 23:26:01.328 #033[1;44m[D]#033[0m [server.go:2774]  |  160.61.161.93|#033[97;42m 200 #033[0m|  23.837213ms|   match|#033[97;44m GET     #033[0m /api/users/current/permissions   r:/api/users/:id/permissions
Feb 27 08:26:01 172.18.0.1 core[21482]: 2020/02/26 23:26:01.352 #033[1;44m[D]#033[0m [server.go:2774]  |  160.61.161.93|#033[97;42m 200 #033[0m|   4.811537ms|   match|#033[97;44m GET     #033[0m /api/projects/2   r:/api/projects/:id([0-9]+)
Feb 27 08:26:01 172.18.0.1 core[21482]: 2020/02/26 23:26:01.434 #033[1;44m[D]#033[0m [server.go:2774]  |  160.61.161.93|#033[97;42m 200 #033[0m|  47.135565ms|   match|#033[97;44m GET     #033[0m /api/projects/2/summary   r:/api/projects/:id([0-9]+)/summary
Feb 27 08:26:02 172.18.0.1 core[21482]: 2020/02/26 23:26:02.794 #033[1;44m[D]#033[0m [server.go:2774]  |  160.61.161.93|#033[97;42m 200 #033[0m|   5.394828ms|   match|#033[97;44m GET     #033[0m /api/systeminfo   r:/api/systeminfo
Feb 27 08:26:02 172.18.0.1 core[21482]: 2020/02/26 23:26:02.798 #033[1;44m[D]#033[0m [server.go:2774]  |  160.61.161.93|#033[97;42m 200 #033[0m|  24.793627ms|   match|#033[97;44m GET     #033[0m /api/repositories   r:/api/repositories
Feb 27 08:26:02 172.18.0.1 core[21482]: 2020/02/26 23:26:02.805 #033[1;44m[D]#033[0m [server.go:2774]  |  160.61.161.93|#033[97;42m 200 #033[0m|   3.889089ms|   match|#033[97;44m GET     #033[0m /api/repositories   r:/api/repositories
Feb 27 08:26:03 172.18.0.1 core[21482]: 2020/02/26 23:26:03.551 #033[1;44m[D]#033[0m [server.go:2774]  |  160.61.161.93|#033[97;42m 200 #033[0m|  25.410661ms|   match|#033[97;44m GET     #033[0m /api/projects/2/members   r:/api/projects/:pid([0-9]+)/members/?:pmid([0-9]+)
Feb 27 08:26:04 172.18.0.1 core[21482]: 2020/02/26 23:26:04.584 #033[1;44m[D]#033[0m [server.go:2774]  |  160.61.161.93|#033[97;42m 200 #033[0m|   4.368175ms|   match|#033[97;44m GET     #033[0m /api/systeminfo   r:/api/systeminfo
Feb 27 08:26:04 172.18.0.1 core[21482]: 2020/02/26 23:26:04.586 #033[1;44m[D]#033[0m [server.go:2774]  |  160.61.161.93|#033[97;42m 200 #033[0m|  20.520816ms|   match|#033[97;44m GET     #033[0m /api/repositories   r:/api/repositories
Feb 27 08:26:04 172.18.0.1 core[21482]: 2020/02/26 23:26:04.610 #033[1;44m[D]#033[0m [server.go:2774]  |  160.61.161.93|#033[97;42m 200 #033[0m|  14.543104ms|   match|#033[97;44m GET     #033[0m /api/repositories   r:/api/repositories
Feb 27 08:26:05 172.18.0.1 core[21482]: 2020/02/26 23:26:05.300 #033[1;44m[D]#033[0m [server.go:2774]  |  160.61.161.93|#033[97;42m 200 #033[0m|  30.215987ms|   match|#033[97;44m GET     #033[0m /api/projects/2/summary   r:/api/projects/:id([0-9]+)/summary
Feb 27 08:26:06 172.18.0.1 core[21482]: 2020/02/26 23:26:06.951 #033[1;44m[D]#033[0m [server.go:2774]  |  160.61.161.93|#033[97;42m 200 #033[0m|  15.558332ms|   match|#033[97;44m GET     #033[0m /api/repositories   r:/api/repositories
Feb 27 08:26:06 172.18.0.1 core[21482]: 2020/02/26 23:26:06.953 #033[1;44m[D]#033[0m [server.go:2774]  |  160.61.161.93|#033[97;42m 200 #033[0m|   3.200624ms|   match|#033[97;44m GET     #033[0m /api/systeminfo   r:/api/systeminfo
Feb 27 08:26:06 172.18.0.1 core[21482]: 2020/02/26 23:26:06.977 #033[1;44m[D]#033[0m [server.go:2774]  |  160.61.161.93|#033[97;42m 200 #033[0m|  14.206479ms|   match|#033[97;44m GET     #033[0m /api/repositories   r:/api/repositories
Feb 27 08:26:11 172.18.0.1 core[21482]: 2020/02/26 23:26:11.972 #033[1;44m[D]#033[0m [server.go:2774]  |  160.61.161.93|#033[97;42m 200 #033[0m|   2.282278ms|   match|#033[97;44m GET     #033[0m /c/log_out   r:/c/log_out
Feb 27 08:26:12 172.18.0.1 core[21482]: 2020/02/26 23:26:12.005 #033[1;44m[D]#033[0m [server.go:2774]  |  160.61.161.93|#033[97;42m 200 #033[0m|   2.290205ms|   match|#033[97;44m GET     #033[0m /api/systeminfo   r:/api/systeminfo
Feb 27 08:26:18 172.18.0.1 core[21482]: 2020/02/26 23:26:18.025 #033[1;44m[D]#033[0m [server.go:2774]  |      127.0.0.1|#033[97;42m 200 #033[0m|    400.286µs|   match|#033[97;44m GET     #033[0m /api/ping   r:/api/ping
Feb 27 08:26:23 172.18.0.1 core[21482]: 2020-02-26T23:26:23Z [INFO] [/core/main.go:154]: capture system signal terminated, to close "closing" channel
Feb 27 08:26:26 172.18.0.1 core[21482]: 2020-02-26T23:26:26Z [INFO] [/core/main.go:160]: Timeout waiting goroutines to exit

jobservice.log
==
Feb 27 08:25:18 172.18.0.1 jobservice[21482]: 2020-02-26T23:25:18Z [INFO] [/replication/adapter/native/adapter.go:42]: the factory for adapter docker-registry registered
Feb 27 08:25:18 172.18.0.1 jobservice[21482]: 2020-02-26T23:25:18Z [INFO] [/replication/adapter/harbor/adapter.go:40]: the factory for adapter harbor registered
Feb 27 08:25:18 172.18.0.1 jobservice[21482]: 2020-02-26T23:25:18Z [INFO] [/replication/adapter/dockerhub/adapter.go:25]: Factory for adapter docker-hub registered
Feb 27 08:25:18 172.18.0.1 jobservice[21482]: 2020-02-26T23:25:18Z [INFO] [/replication/adapter/huawei/huawei_adapter.go:27]: the factory of Huawei adapter was registered
Feb 27 08:25:18 172.18.0.1 jobservice[21482]: 2020-02-26T23:25:18Z [INFO] [/replication/adapter/googlegcr/adapter.go:29]: the factory for adapter google-gcr registered
Feb 27 08:25:18 172.18.0.1 jobservice[21482]: 2020-02-26T23:25:18Z [INFO] [/replication/adapter/awsecr/adapter.go:47]: the factory for adapter aws-ecr registered
Feb 27 08:25:18 172.18.0.1 jobservice[21482]: 2020-02-26T23:25:18Z [INFO] [/replication/adapter/azurecr/adapter.go:15]: Factory for adapter azure-acr registered
Feb 27 08:25:18 172.18.0.1 jobservice[21482]: 2020-02-26T23:25:18Z [INFO] [/replication/adapter/aliacr/adapter.go:26]: the factory for adapter ali-acr registered
Feb 27 08:25:18 172.18.0.1 jobservice[21482]: 2020-02-26T23:25:18Z [INFO] [/replication/adapter/jfrog/adapter.go:30]: the factory of jfrog artifactory adapter was registered
Feb 27 08:25:18 172.18.0.1 jobservice[21482]: 2020-02-26T23:25:18Z [INFO] [/replication/adapter/quayio/adapter.go:34]: the factory of Quay.io adapter was registered
Feb 27 08:25:18 172.18.0.1 jobservice[21482]: 2020-02-26T23:25:18Z [INFO] [/replication/adapter/helmhub/adapter.go:30]: the factory for adapter helm-hub registered
Feb 27 08:25:18 172.18.0.1 jobservice[21482]: 2020-02-26T23:25:18Z [INFO] [/replication/adapter/gitlab/adapter.go:19]: the factory for adapter gitlab registered
Feb 27 08:25:18 172.18.0.1 jobservice[21482]: 2020-02-26T23:25:18Z [INFO] [/common/config/store/driver/rest.go:24]: get configuration from url: http://core:8080/api/internal/configurations
Feb 27 08:25:18 172.18.0.1 jobservice[21482]: 2020-02-26T23:25:18Z [INFO] [/jobservice/logger/sweeper_controller.go:97]: 0 outdated log entries are sweepped by sweeper *sweeper.FileSweeper
Feb 27 08:25:18 172.18.0.1 jobservice[21482]: 2020-02-26T23:25:18Z [INFO] [/common/dao/base.go:84]: Registering database: type-PostgreSQL host-postgresql port-5432 databse-registry sslmode-"disable"
Feb 27 08:25:18 172.18.0.1 jobservice[21482]: 2020-02-26T23:25:18Z [INFO] [/common/dao/base.go:89]: Register database completed
Feb 27 08:25:18 172.18.0.1 jobservice[21482]: 2020-02-26T23:25:18Z [INFO] [/jobservice/migration/manager.go:111]: No migration needed
Feb 27 08:25:18 172.18.0.1 jobservice[21482]: 2020-02-26T23:25:18Z [INFO] [/jobservice/worker/cworker/c_worker.go:424]: Register job *replication.Replication with name REPLICATION
Feb 27 08:25:18 172.18.0.1 jobservice[21482]: 2020-02-26T23:25:18Z [INFO] [/jobservice/worker/cworker/c_worker.go:424]: Register job *replication.Scheduler with name IMAGE_REPLICATE
Feb 27 08:25:18 172.18.0.1 jobservice[21482]: 2020-02-26T23:25:18Z [INFO] [/jobservice/worker/cworker/c_worker.go:424]: Register job *sample.Job with name DEMO
Feb 27 08:25:18 172.18.0.1 jobservice[21482]: 2020-02-26T23:25:18Z [INFO] [/jobservice/worker/cworker/c_worker.go:424]: Register job *scan.Job with name IMAGE_SCAN
Feb 27 08:25:18 172.18.0.1 jobservice[21482]: 2020-02-26T23:25:18Z [INFO] [/jobservice/worker/cworker/c_worker.go:424]: Register job *all.Job with name IMAGE_SCAN_ALL
Feb 27 08:25:18 172.18.0.1 jobservice[21482]: 2020-02-26T23:25:18Z [INFO] [/jobservice/worker/cworker/c_worker.go:424]: Register job *gc.GarbageCollector with name IMAGE_GC
Feb 27 08:25:18 172.18.0.1 jobservice[21482]: 2020-02-26T23:25:18Z [INFO] [/jobservice/worker/cworker/c_worker.go:424]: Register job *retention.Job with name RETENTION
Feb 27 08:25:18 172.18.0.1 jobservice[21482]: 2020-02-26T23:25:18Z [INFO] [/jobservice/worker/cworker/c_worker.go:424]: Register job *scheduler.PeriodicJob with name SCHEDULER
Feb 27 08:25:18 172.18.0.1 jobservice[21482]: 2020-02-26T23:25:18Z [INFO] [/jobservice/worker/cworker/c_worker.go:424]: Register job *notification.WebhookJob with name WEBHOOK
Feb 27 08:25:18 172.18.0.1 jobservice[21482]: 2020-02-26T23:25:18Z [INFO] [/jobservice/period/enqueuer.go:72]: Scheduler: periodic enqueuer is started
Feb 27 08:25:18 172.18.0.1 jobservice[21482]: 2020-02-26T23:25:18Z [INFO] [/jobservice/worker/cworker/c_worker.go:151]: Basic worker is started
Feb 27 08:25:18 172.18.0.1 jobservice[21482]: 2020-02-26T23:25:18Z [INFO] [/jobservice/lcm/controller.go:86]: Status restoring loop is started
Feb 27 08:25:18 172.18.0.1 jobservice[21482]: 2020-02-26T23:25:18Z [INFO] [/jobservice/hook/hook_agent.go:146]: Hook event retrying loop is started
Feb 27 08:25:18 172.18.0.1 jobservice[21482]: 2020-02-26T23:25:18Z [INFO] [/jobservice/worker/cworker/reaper.go:57]: Reaper is started
Feb 27 08:25:18 172.18.0.1 jobservice[21482]: 2020-02-26T23:25:18Z [INFO] [/jobservice/runtime/bootstrap.go:200]: API server is serving at 8080 with [http] mode at node [5132b7029589:172.18.0.9]
Feb 27 08:26:22 172.18.0.1 jobservice[21482]: 2020-02-26T23:26:22Z [INFO] [/jobservice/api/server.go:101]: API server is stopped
Feb 27 08:26:22 172.18.0.1 jobservice[21482]: 2020-02-26T23:26:22Z [INFO] [/jobservice/lcm/controller.go:129]: Status restoring loop is stopped
Feb 27 08:26:22 172.18.0.1 jobservice[21482]: 2020-02-26T23:26:22Z [INFO] [/jobservice/hook/hook_agent.go:193]: Hook event retrying loop exit
Feb 27 08:26:22 172.18.0.1 jobservice[21482]: 2020-02-26T23:26:22Z [INFO] [/jobservice/worker/cworker/reaper.go:67]: Reaper is stopped
Feb 27 08:26:22 172.18.0.1 jobservice[21482]: 2020-02-26T23:26:22Z [INFO] [/jobservice/period/enqueuer.go:77]: Scheduler: periodic enqueuer is stopped
Feb 27 08:26:22 172.18.0.1 jobservice[21482]: 2020-02-26T23:26:22Z [INFO] [/jobservice/logger/sweeper_controller.go:83]: sweeper *sweeper.FileSweeper exit
Feb 27 08:26:22 172.18.0.1 jobservice[21482]: 2020-02-26T23:26:22Z [INFO] [/jobservice/worker/cworker/c_worker.go:139]: Basic worker is stopped


portal.log
==
Feb 27 08:25:17 172.18.0.1 portal[21482]: 172.18.0.8 - - [26/Feb/2020:23:25:17 +0000] "GET / HTTP/1.1" 200 718 "-" "Go-http-client/1.1"
Feb 27 08:25:27 172.18.0.1 portal[21482]: 172.18.0.8 - - [26/Feb/2020:23:25:27 +0000] "GET / HTTP/1.1" 200 718 "-" "Go-http-client/1.1"
Feb 27 08:25:37 172.18.0.1 portal[21482]: 172.18.0.8 - - [26/Feb/2020:23:25:37 +0000] "GET / HTTP/1.1" 200 718 "-" "Go-http-client/1.1"
Feb 27 08:25:47 172.18.0.1 portal[21482]: 127.0.0.1 - - [26/Feb/2020:23:25:47 +0000] "GET / HTTP/1.1" 200 718 "-" "curl/7.59.0"
Feb 27 08:25:47 172.18.0.1 portal[21482]: 172.18.0.8 - - [26/Feb/2020:23:25:47 +0000] "GET / HTTP/1.1" 200 718 "-" "Go-http-client/1.1"
Feb 27 08:25:50 172.18.0.1 portal[21482]: 172.18.0.10 - - [26/Feb/2020:23:25:50 +0000] "GET / HTTP/1.1" 200 718 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"
Feb 27 08:25:50 172.18.0.1 portal[21482]: 172.18.0.10 - - [26/Feb/2020:23:25:50 +0000] "GET /styles.701dc5ee3007bd83bfa4.css HTTP/1.1" 200 172565 "https://harbor.yskotc.org:20443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"
Feb 27 08:25:50 172.18.0.1 portal[21482]: 172.18.0.10 - - [26/Feb/2020:23:25:50 +0000] "GET /runtime.9ad22a88fcc70a015907.js HTTP/1.1" 200 736 "https://harbor.yskotc.org:20443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"
Feb 27 08:25:50 172.18.0.1 portal[21482]: 172.18.0.10 - - [26/Feb/2020:23:25:50 +0000] "GET /scripts.7fa3fa51e1a86dfba2c8.js HTTP/1.1" 200 222620 "https://harbor.yskotc.org:20443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"
Feb 27 08:25:50 172.18.0.1 portal[21482]: 172.18.0.10 - - [26/Feb/2020:23:25:50 +0000] "GET /main.93d9806e0f1f6ecb9a7f.js HTTP/1.1" 200 1438255 "https://harbor.yskotc.org:20443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"
Feb 27 08:25:51 172.18.0.1 portal[21482]: 172.18.0.10 - - [26/Feb/2020:23:25:50 +0000] "GET /i18n/lang/en-us-lang.json HTTP/1.1" 200 19709 "https://harbor.yskotc.org:20443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"
Feb 27 08:25:51 172.18.0.1 portal[21482]: 172.18.0.10 - - [26/Feb/2020:23:25:51 +0000] "GET /setting.json HTTP/1.1" 200 203 "https://harbor.yskotc.org:20443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"
Feb 27 08:25:51 172.18.0.1 portal[21482]: 172.18.0.10 - - [26/Feb/2020:23:25:51 +0000] "GET /images/harbor-logo.svg HTTP/1.1" 200 1797 "https://harbor.yskotc.org:20443/harbor/sign-in?redirect_url=%2Fharbor%2Fprojects" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"
Feb 27 08:25:57 172.18.0.1 portal[21482]: 172.18.0.8 - - [26/Feb/2020:23:25:57 +0000] "GET / HTTP/1.1" 200 718 "-" "Go-http-client/1.1"
Feb 27 08:26:07 172.18.0.1 portal[21482]: 172.18.0.8 - - [26/Feb/2020:23:26:07 +0000] "GET / HTTP/1.1" 200 718 "-" "Go-http-client/1.1"
Feb 27 08:26:17 172.18.0.1 portal[21482]: 127.0.0.1 - - [26/Feb/2020:23:26:17 +0000] "GET / HTTP/1.1" 200 718 "-" "curl/7.59.0"
Feb 27 08:26:17 172.18.0.1 portal[21482]: 172.18.0.8 - - [26/Feb/2020:23:26:17 +0000] "GET / HTTP/1.1" 200 718 "-" "Go-http-client/1.1"

postgresql.log
==
Feb 27 08:25:17 172.18.0.1 postgresql[21482]: LOG:  database system was interrupted; last known up at 2020-02-26 00:50:30 UTC
Feb 27 08:25:17 172.18.0.1 postgresql[21482]: LOG:  database system was not properly shut down; automatic recovery in progress
Feb 27 08:25:17 172.18.0.1 postgresql[21482]: LOG:  invalid record length at 0/17115E8: wanted 24, got 0
Feb 27 08:25:17 172.18.0.1 postgresql[21482]: LOG:  redo is not required
Feb 27 08:25:17 172.18.0.1 postgresql[21482]: LOG:  MultiXact member wraparound protections are now enabled
Feb 27 08:25:17 172.18.0.1 postgresql[21482]: LOG:  database system is ready to accept connections
Feb 27 08:25:17 172.18.0.1 postgresql[21482]: LOG:  autovacuum launcher started
Feb 27 08:25:17 172.18.0.1 postgresql[21482]: LOG:  incomplete startup packet
Feb 27 08:25:18 172.18.0.1 postgresql[21482]: LOG:  incomplete startup packet


proxy.log
==
Feb 27 08:25:48 172.18.0.1 proxy[21482]: 127.0.0.1 - "GET / HTTP/1.1" 308 171 "-" "curl/7.59.0" 0.000 - .
Feb 27 08:25:50 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET / HTTP/1.1" 200 718 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.001 0.000 .
Feb 27 08:25:50 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /styles.701dc5ee3007bd83bfa4.css HTTP/1.1" 200 172872 "https://harbor.yskotc.org:20443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.043 0.042 .
Feb 27 08:25:50 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /runtime.9ad22a88fcc70a015907.js HTTP/1.1" 200 736 "https://harbor.yskotc.org:20443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.001 0.001 .
Feb 27 08:25:50 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /scripts.7fa3fa51e1a86dfba2c8.js HTTP/1.1" 200 223024 "https://harbor.yskotc.org:20443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.040 0.040 .
Feb 27 08:25:50 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /main.93d9806e0f1f6ecb9a7f.js HTTP/1.1" 200 1440866 "https://harbor.yskotc.org:20443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.087 0.087 .
Feb 27 08:25:51 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /i18n/lang/en-us-lang.json HTTP/1.1" 200 19739 "https://harbor.yskotc.org:20443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.005 0.004 .
Feb 27 08:25:51 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /setting.json HTTP/1.1" 200 203 "https://harbor.yskotc.org:20443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.001 0.000 .
Feb 27 08:25:51 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /api/systeminfo HTTP/1.1" 200 276 "https://harbor.yskotc.org:20443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.004 0.004 .
Feb 27 08:25:51 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /api/users/current HTTP/1.1" 401 37 "https://harbor.yskotc.org:20443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.003 0.003 .
Feb 27 08:25:51 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /api/users/current HTTP/1.1" 401 37 "https://harbor.yskotc.org:20443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.004 0.003 .
Feb 27 08:25:51 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /api/systeminfo HTTP/1.1" 200 276 "https://harbor.yskotc.org:20443/harbor/sign-in?redirect_url=%2Fharbor%2Fprojects" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.006 0.005 .
Feb 27 08:25:51 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /images/harbor-logo.svg HTTP/1.1" 200 1797 "https://harbor.yskotc.org:20443/harbor/sign-in?redirect_url=%2Fharbor%2Fprojects" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.001 0.000 .
Feb 27 08:25:58 172.18.0.1 proxy[21482]: 160.61.161.93 - "POST /c/login HTTP/1.1" 200 0 "https://harbor.yskotc.org:20443/harbor/sign-in?redirect_url=%2Fharbor%2Fprojects" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.017 0.017 .
Feb 27 08:25:58 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /api/users/current HTTP/1.1" 200 235 "https://harbor.yskotc.org:20443/harbor/sign-in?redirect_url=%2Fharbor%2Fprojects" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.002 0.002 .
Feb 27 08:25:58 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /api/scanners HTTP/1.1" 200 2 "https://harbor.yskotc.org:20443/harbor/projects" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.008 0.008 .
Feb 27 08:25:58 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /api/configurations HTTP/1.1" 200 610 "https://harbor.yskotc.org:20443/harbor/projects" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.007 0.007 .
Feb 27 08:25:58 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /api/systeminfo/volumes HTTP/1.1" 200 90 "https://harbor.yskotc.org:20443/harbor/projects" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.006 0.006 .
Feb 27 08:25:58 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /api/statistics HTTP/1.1" 200 97 "https://harbor.yskotc.org:20443/harbor/projects" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.028 0.028 .
Feb 27 08:25:58 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /api/projects?page=1&page_size=15 HTTP/1.1" 200 369 "https://harbor.yskotc.org:20443/harbor/projects" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.036 0.036 .
Feb 27 08:26:01 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /api/projects/2 HTTP/1.1" 200 259 "https://harbor.yskotc.org:20443/harbor/projects" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.021 0.021 .
Feb 27 08:26:01 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /api/users/current/permissions?scope=/project/2&relative=true HTTP/1.1" 200 546 "https://harbor.yskotc.org:20443/harbor/projects" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.025 0.025 .
Feb 27 08:26:01 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /api/projects/2 HTTP/1.1" 200 259 "https://harbor.yskotc.org:20443/harbor/projects" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.006 0.005 .
Feb 27 08:26:01 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /api/projects/2/summary HTTP/1.1" 200 171 "https://harbor.yskotc.org:20443/harbor/projects/2/summary" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.048 0.048 .
Feb 27 08:26:02 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /api/systeminfo HTTP/1.1" 200 276 "https://harbor.yskotc.org:20443/harbor/projects/2/repositories" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.007 0.007 .
Feb 27 08:26:02 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /api/repositories?page=1&page_size=15&project_id=2 HTTP/1.1" 200 2 "https://harbor.yskotc.org:20443/harbor/projects/2/repositories" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.026 0.026 .
Feb 27 08:26:02 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /api/repositories?page=1&page_size=15&project_id=2 HTTP/1.1" 200 2 "https://harbor.yskotc.org:20443/harbor/projects/2/repositories" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.004 0.004 .
Feb 27 08:26:03 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /api/projects/2/members?entityname= HTTP/1.1" 200 150 "https://harbor.yskotc.org:20443/harbor/projects/2/members" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.027 0.026 .
Feb 27 08:26:04 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /api/systeminfo HTTP/1.1" 200 276 "https://harbor.yskotc.org:20443/harbor/projects/2/repositories" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.006 0.006 .
Feb 27 08:26:04 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /api/repositories?page=1&page_size=15&project_id=2 HTTP/1.1" 200 2 "https://harbor.yskotc.org:20443/harbor/projects/2/repositories" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.022 0.022 .
Feb 27 08:26:04 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /api/repositories?page=1&page_size=15&project_id=2 HTTP/1.1" 200 2 "https://harbor.yskotc.org:20443/harbor/projects/2/repositories" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.016 0.016 .
Feb 27 08:26:05 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /api/projects/2/summary HTTP/1.1" 200 171 "https://harbor.yskotc.org:20443/harbor/projects/2/summary" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.032 0.031 .
Feb 27 08:26:06 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /api/repositories?page=1&page_size=15&project_id=2 HTTP/1.1" 200 2 "https://harbor.yskotc.org:20443/harbor/projects/2/repositories" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.018 0.016 .
Feb 27 08:26:06 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /api/systeminfo HTTP/1.1" 200 276 "https://harbor.yskotc.org:20443/harbor/projects/2/repositories" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.005 0.005 .
Feb 27 08:26:06 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /api/repositories?page=1&page_size=15&project_id=2 HTTP/1.1" 200 2 "https://harbor.yskotc.org:20443/harbor/projects/2/repositories" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.016 0.016 .
Feb 27 08:26:11 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /c/log_out HTTP/1.1" 200 0 "https://harbor.yskotc.org:20443/harbor/projects/2/repositories" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.003 0.003 .
Feb 27 08:26:12 172.18.0.1 proxy[21482]: 160.61.161.93 - "GET /api/systeminfo HTTP/1.1" 200 276 "https://harbor.yskotc.org:20443/harbor/sign-in?signout=true&redirect_url=%2Fharbor%2Fprojects%2F2%2Frepositories" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" 0.004 0.004 .
Feb 27 08:26:18 172.18.0.1 proxy[21482]: 127.0.0.1 - "GET / HTTP/1.1" 308 171 "-" "curl/7.59.0" 0.000 - .


redis.log
==Feb 27 08:25:17 172.18.0.1 redis[21482]: 1:C 26 Feb 23:25:17.219 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
Feb 27 08:25:17 172.18.0.1 redis[21482]: 1:C 26 Feb 23:25:17.219 # Redis version=4.0.14, bits=64, commit=00000000, modified=0, pid=1, just started
Feb 27 08:25:17 172.18.0.1 redis[21482]: 1:C 26 Feb 23:25:17.219 # Configuration loaded
Feb 27 08:25:17 172.18.0.1 redis[21482]:                 _._                                                  
Feb 27 08:25:17 172.18.0.1 redis[21482]:            _.-``__ ''-._                                             
Feb 27 08:25:17 172.18.0.1 redis[21482]:       _.-``    `.  `_.  ''-._           Redis 4.0.14 (00000000/0) 64 bit
Feb 27 08:25:17 172.18.0.1 redis[21482]:   .-`` .-```.  ```\/    _.,_ ''-._                                   
Feb 27 08:25:17 172.18.0.1 redis[21482]:  (    '      ,       .-`  | `,    )     Running in standalone mode
Feb 27 08:25:17 172.18.0.1 redis[21482]:  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
Feb 27 08:25:17 172.18.0.1 redis[21482]:  |    `-._   `._    /     _.-'    |     PID: 1
Feb 27 08:25:17 172.18.0.1 redis[21482]:   `-._    `-._  `-./  _.-'    _.-'                                   
Feb 27 08:25:17 172.18.0.1 redis[21482]:  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
Feb 27 08:25:17 172.18.0.1 redis[21482]:  |    `-._`-._        _.-'_.-'    |           http://redis.io        
Feb 27 08:25:17 172.18.0.1 redis[21482]:   `-._    `-._`-.__.-'_.-'    _.-'                                   
Feb 27 08:25:17 172.18.0.1 redis[21482]:  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
Feb 27 08:25:17 172.18.0.1 redis[21482]:  |    `-._`-._        _.-'_.-'    |                                  
Feb 27 08:25:17 172.18.0.1 redis[21482]:   `-._    `-._`-.__.-'_.-'    _.-'                                   
Feb 27 08:25:17 172.18.0.1 redis[21482]:       `-._    `-.__.-'    _.-'                                       
Feb 27 08:25:17 172.18.0.1 redis[21482]:           `-._        _.-'                                           
Feb 27 08:25:17 172.18.0.1 redis[21482]:               `-.__.-'                                               
Feb 27 08:25:17 172.18.0.1 redis[21482]: 
Feb 27 08:25:17 172.18.0.1 redis[21482]: 1:M 26 Feb 23:25:17.221 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
Feb 27 08:25:17 172.18.0.1 redis[21482]: 1:M 26 Feb 23:25:17.221 # Server initialized
Feb 27 08:25:17 172.18.0.1 redis[21482]: 1:M 26 Feb 23:25:17.221 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
Feb 27 08:25:17 172.18.0.1 redis[21482]: 1:M 26 Feb 23:25:17.222 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
Feb 27 08:25:17 172.18.0.1 redis[21482]: 1:M 26 Feb 23:25:17.222 * DB loaded from disk: 0.001 seconds
Feb 27 08:25:17 172.18.0.1 redis[21482]: 1:M 26 Feb 23:25:17.222 * Ready to accept connections
Feb 27 08:26:26 172.18.0.1 redis[21482]: 1:signal-handler (1582759586) Received SIGTERM scheduling shutdown...
Feb 27 08:26:26 172.18.0.1 redis[21482]: 1:M 26 Feb 23:26:26.540 # User requested shutdown...
Feb 27 08:26:26 172.18.0.1 redis[21482]: 1:M 26 Feb 23:26:26.540 * Saving the final RDB snapshot before exiting.
Feb 27 08:26:26 172.18.0.1 redis[21482]: 1:M 26 Feb 23:26:26.544 * DB saved on disk
Feb 27 08:26:26 172.18.0.1 redis[21482]: 1:M 26 Feb 23:26:26.544 * Removing the pid file.
Feb 27 08:26:26 172.18.0.1 redis[21482]: 1:M 26 Feb 23:26:26.544 # Redis is now ready to exit, bye bye...


registry.log
==
Feb 27 08:25:17 172.18.0.1 registry[21482]: ls: /harbor_cust_cert: No such file or directory
Feb 27 08:25:17 172.18.0.1 registry[21482]: time="2020-02-26T23:25:17.238847174Z" level=info msg="debug server listening localhost:5001" 
Feb 27 08:25:17 172.18.0.1 registry[21482]: time="2020-02-26T23:25:17.239245276Z" level=info msg="configuring endpoint harbor (http://core:8080/service/notifications), timeout=3s, headers=map[]" go.version=go1.12.12 instance.id=93885684-9bfc-49e4-9389-29cc25f3f0a7 service=registry version=v2.7.1.m 
Feb 27 08:25:17 172.18.0.1 registry[21482]: time="2020-02-26T23:25:17.245401677Z" level=info msg="using redis blob descriptor cache" go.version=go1.12.12 instance.id=93885684-9bfc-49e4-9389-29cc25f3f0a7 service=registry version=v2.7.1.m 
Feb 27 08:25:17 172.18.0.1 registry[21482]: time="2020-02-26T23:25:17.245871923Z" level=info msg="listening on [::]:5000" go.version=go1.12.12 instance.id=93885684-9bfc-49e4-9389-29cc25f3f0a7 service=registry version=v2.7.1.m 
Feb 27 08:25:17 172.18.0.1 registry[21482]: 172.18.0.8 - - [26/Feb/2020:23:25:17 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
Feb 27 08:25:27 172.18.0.1 registry[21482]: 172.18.0.8 - - [26/Feb/2020:23:25:27 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
Feb 27 08:25:37 172.18.0.1 registry[21482]: 172.18.0.8 - - [26/Feb/2020:23:25:37 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
Feb 27 08:25:47 172.18.0.1 registry[21482]: 127.0.0.1 - - [26/Feb/2020:23:25:47 +0000] "GET / HTTP/1.1" 200 0 "" "curl/7.59.0"
Feb 27 08:25:47 172.18.0.1 registry[21482]: 172.18.0.8 - - [26/Feb/2020:23:25:47 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
Feb 27 08:25:57 172.18.0.1 registry[21482]: 172.18.0.8 - - [26/Feb/2020:23:25:57 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
Feb 27 08:26:07 172.18.0.1 registry[21482]: 172.18.0.8 - - [26/Feb/2020:23:26:07 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
Feb 27 08:26:17 172.18.0.1 registry[21482]: 127.0.0.1 - - [26/Feb/2020:23:26:17 +0000] "GET / HTTP/1.1" 200 0 "" "curl/7.59.0"
Feb 27 08:26:17 172.18.0.1 registry[21482]: 172.18.0.8 - - [26/Feb/2020:23:26:17 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"


registryctl.log
==
Feb 27 08:25:17 172.18.0.1 registry[21482]: ls: /harbor_cust_cert: No such file or directory
Feb 27 08:25:17 172.18.0.1 registry[21482]: time="2020-02-26T23:25:17.238847174Z" level=info msg="debug server listening localhost:5001" 
Feb 27 08:25:17 172.18.0.1 registry[21482]: time="2020-02-26T23:25:17.239245276Z" level=info msg="configuring endpoint harbor (http://core:8080/service/notifications), timeout=3s, headers=map[]" go.version=go1.12.12 instance.id=93885684-9bfc-49e4-9389-29cc25f3f0a7 service=registry version=v2.7.1.m 
Feb 27 08:25:17 172.18.0.1 registry[21482]: time="2020-02-26T23:25:17.245401677Z" level=info msg="using redis blob descriptor cache" go.version=go1.12.12 instance.id=93885684-9bfc-49e4-9389-29cc25f3f0a7 service=registry version=v2.7.1.m 
Feb 27 08:25:17 172.18.0.1 registry[21482]: time="2020-02-26T23:25:17.245871923Z" level=info msg="listening on [::]:5000" go.version=go1.12.12 instance.id=93885684-9bfc-49e4-9389-29cc25f3f0a7 service=registry version=v2.7.1.m 
Feb 27 08:25:17 172.18.0.1 registry[21482]: 172.18.0.8 - - [26/Feb/2020:23:25:17 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
Feb 27 08:25:27 172.18.0.1 registry[21482]: 172.18.0.8 - - [26/Feb/2020:23:25:27 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
Feb 27 08:25:37 172.18.0.1 registry[21482]: 172.18.0.8 - - [26/Feb/2020:23:25:37 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
Feb 27 08:25:47 172.18.0.1 registry[21482]: 127.0.0.1 - - [26/Feb/2020:23:25:47 +0000] "GET / HTTP/1.1" 200 0 "" "curl/7.59.0"
Feb 27 08:25:47 172.18.0.1 registry[21482]: 172.18.0.8 - - [26/Feb/2020:23:25:47 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
Feb 27 08:25:57 172.18.0.1 registry[21482]: 172.18.0.8 - - [26/Feb/2020:23:25:57 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
Feb 27 08:26:07 172.18.0.1 registry[21482]: 172.18.0.8 - - [26/Feb/2020:23:26:07 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
Feb 27 08:26:17 172.18.0.1 registry[21482]: 127.0.0.1 - - [26/Feb/2020:23:26:17 +0000] "GET / HTTP/1.1" 200 0 "" "curl/7.59.0"
Feb 27 08:26:17 172.18.0.1 registry[21482]: 172.18.0.8 - - [26/Feb/2020:23:26:17 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"

**Comment by reasonerjt** [comment]
Thanks @bolrock @astriker 

This error is relevant 
```
Feb 26 10:47:59 172.28.0.1 registry[1102]: time="2020-02-26T10:47:59.006388078Z" level=error msg="retryingsink: error writing events: httpSink{http://core:8080/service/notifications}: response status 404 Not Found unaccepted, retrying" 
```

Because the record was added by the event handler in core after image is pushed, if that responds 404, the record won't be added.
I'll install a build and see if I can reproduce.

**Comment by wy65701436** [comment]
hi @bolrock @astriker I cannot reproduce it in my env, can you share the confiuragion of your Harbor? and please update a full stack of logs with a tar or zip file, thanks.

**Comment by reasonerjt** [comment]
@bolrock @astriker are you both using online installer, could you try the offline installer?

**Comment by astriker** [comment]
> @bolrock @astriker are you both using online installer, could you try the offline installer?

When I used the offline installer v1.10.1, It had this problem.
But When I used the online installer v1.10.1 at another server, It's OK.
In my case, this problem is solved.

**Comment by bolrock** [comment]
I also just tried to start again from zero for using the `online installer` downloaed from 
> https://github.com/goharbor/harbor/releases/download/v1.10.1/harbor-online-installer-v1.10.1.tgz

Then decompress, cd harbor, edited the `harbor.yml` for changing hostname, port (8080) and commented https.
Then `sudo ./install.sh`.
The images are downloaded, and the install process goes fine without errors.
But ... my image is still not shown in the library project
Same problem when using offline installer.
The registry.log is filled endless with
```
Mar  2 13:46:54 172.20.0.1 registry[1247]: time="2020-03-02T13:46:54.886548832Z" level=warning msg="httpSink{http://core:8080/service/notifications} encountered too many errors, backing off" 
Mar  2 13:46:55 172.20.0.1 registry[1247]: time="2020-03-02T13:46:55.900362522Z" level=error msg="retryingsink: error writing events: httpSink{http://core:8080/service/notifications}: response status 404 Not Found unaccepted, retrying" 

```

**Comment by bolrock** [comment]
I don't understand what's going on.

In the registry.log I can see

```
Mar  3 07:29:21 172.25.0.1 registry[1247]: time="2020-03-03T07:29:21.096192802Z" level=info msg="configuring endpoint harbor (http://core:8080/service/notifications), timeout=3s, headers=map[]" go.version=go1.12.12 instance.id=10ccdfa7-06cb-4035-b0a0-696092b91f08 service=registry version=v2.7.1.m 
```

Outside of any containers I can't reach that endpoint

> curl http://core:8080/service/notifications
> curl: (6) Could not resolve host: core

But it's working with it's ip

> curl http://172.25.0.8:8080/service/notifications
> Method Not Allowed

If I go into `core containter` with 

> docker exec -it harbor-core bash

> harbor [ /harbor ]$ curl http://core:8080
> Cannot resolve hostname 'core' in explicit-proxy request.

But 

> harbor [ /harbor ]$ curl http://172.25.0.8:8080/service/notifications

hangs till ctrl-c

Now If I edit  `common/config/registry/config.yml` for replacing the endpoint url `core `with `172.25.0.8` and restart the registry container, after pushing an image, I still can't view it but now the logs show me

```
Mar  3 07:34:50 172.25.0.1 registry[1247]: time="2020-03-03T07:34:50.132666088Z" level=info msg="configuring endpoint harbor (http://172.25.0.8:8080/service/notifications), timeout=3s, headers=map[]" go.version=go1.12.12 instance.id=485f84b0-7acb-424d-bb70-c8cd567826de service=registry version=v2.7.1.m 
...
Mar  3 07:41:36 172.25.0.1 registry[1247]: time="2020-03-03T07:41:36.218522629Z" level=error msg="retryingsink: error writing events: httpSink{http://172.25.0.8:8080/service/notifications}: error posting: Post http://172.25.0.8:8080/service/notifications: net/http: request canceled (Client.Timeout exceeded while awaiting headers), retrying" 
Mar  3 07:41:36 172.25.0.1 registry[1247]: time="2020-03-03T07:41:36.218564629Z" level=warning msg="httpSink{http://172.25.0.8:8080/service/notifications} encountered too many errors, backing off" 

```

And I don't know if it's important but many containers remains unhealthy

```
dccd25e94050        goharbor/nginx-photon:v1.10.1                             "nginx -g 'daemon of…"   27 minutes ago      Up 27 minutes (unhealthy)   0.0.0.0:8080->8080/tcp                  nginx
80b577dcbdd3        goharbor/harbor-jobservice:v1.10.1                        "/harbor/harbor_jobs…"   27 minutes ago      Up 27 minutes (unhealthy)                                           harbor-jobservice
b62e477eb92f        goharbor/harbor-core:v1.10.1                              "/harbor/harbor_core"    28 minutes ago      Up 27 minutes (unhealthy)                                           harbor-core
6dfde559ae76        goharbor/harbor-registryctl:v1.10.1                       "/home/harbor/start.…"   28 minutes ago      Up 28 minutes (unhealthy)                                           registryctl
b083cb0638c5        goharbor/harbor-portal:v1.10.1                            "nginx -g 'daemon of…"   28 minutes ago      Up 28 minutes (unhealthy)   8080/tcp                                harbor-portal
04bd39b1ce60        goharbor/registry-photon:v2.7.1-patch-2819-2553-v1.10.1   "/home/harbor/entryp…"   28 minutes ago      Up 22 minutes (healthy)     5000/tcp                                registry
851faa3958c8        goharbor/redis-photon:v1.10.1                             "redis-server /etc/r…"   28 minutes ago      Up 28 minutes (healthy)     6379/tcp                                redis
2b3d236c0efb        goharbor/harbor-db:v1.10.1                                "/docker-entrypoint.…"   28 minutes ago      Up 27 minutes (healthy)     5432/tcp                                harbor-db
0f3acefa0261        goharbor/harbor-log:v1.10.1                               "/bin/sh -c /usr/loc…"   28 minutes ago      Up 28 minutes (healthy)     127.0.0.1:1514->10514/tcp               harbor-log

```

**Comment by bolrock** [comment]
Ok, I just found what's wrong.

It's because I'm behind a proxy.

My `~/.docker/config.json` contains
```
{
 "proxies":
 {
   "default":
   {
     "httpProxy": "http://myproxy.mydomain.intra:8080",
     "httpsProxy": "http://myproxy.mydomain.intra:8080",
     "noProxy": "localhost,.mydomain.intra"
   }
 }
}
```
If I remove that config file and restart docker, it's working.  But I want to keep it.
And I don't known what to do.

In the `harbor.yml` I tried adding no_proxy: `127.0.0.1,localhost,.local,.internal,log,db,redis,nginx,core,portal,postgresql,jobservice,registry,registryctl,clair
`
but it's not overriding the docker config.

**Comment by alinsilvian** [comment]
I get the same behaviour when using S3 as a storage_service. So far it reproduced  5 out of 5 times.  
I replicate projects from another registry (docker-registry in my case). After replication is complete I can see all the projects but the repositories in the projects show  0 objects while the artifacts number is non-0. 
If I run the replication again the logs show that the blobs are already there so no need to re-copy. I was unable to pull images though.

**Comment by astriker** [comment]
How about trying at another server? I did succeed.
I was likely to feel your pain.
And another option is just to use ip address instead of your own xxx.domain.com.
I hope you solve the problem.



> Ok, I just found what's wrong.
> 
> It's because I'm behind a proxy.
> 
> My `~/.docker/config.json` contains
> 
> ```
> {
>  "proxies":
>  {
>    "default":
>    {
>      "httpProxy": "http://myproxy.mydomain.intra:8080",
>      "httpsProxy": "http://myproxy.mydomain.intra:8080",
>      "noProxy": "localhost,.mydomain.intra"
>    }
>  }
> }
> ```
> 
> If I remove that config file and restart docker, it's working. But I want to keep it.
> And I don't known what to do.
> 
> In the `harbor.yml` I tried adding
> 
> > no_proxy: 127.0.0.1,localhost,.local,.internal,log,db,redis,nginx,core,portal,postgresql,jobservice,registry,registryctl,clair
> 
> but it's not overriding the docker config.

**Comment by reasonerjt** [comment]
@bolrock 

I believe the following settings are on your docker host where Harbor were installed?

```
{
 "proxies":
 {
   "default":
   {
     "httpProxy": "http://myproxy.mydomain.intra:8080",
     "httpsProxy": "http://myproxy.mydomain.intra:8080",
     "noProxy": "localhost,.mydomain.intra"
   }
 }
}
```

The proxy is the root cause, the webhook between Harbor containers were sent via the proxy and failed to reach the target, you can update the `config.json` to make sure communications between harbor containers don't go via proxy.  Updating harbor.yml will NOT impact docker's config, which seems has higher priority.

**Comment by reasonerjt** [comment]
Closing due to inactivity

**Comment by osaffer** [comment]
Hi,
Did you find a solution?
Harbor has been installed in kubernetes with helm, the cluster is behind a corporate proxy.
I tried to set also the no_proxy parameter in values file, but without success.

Inside the harbor-registry or any other pods, when I do 
curl http://harbor-core/service/notifications
<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<title>404 - Page Not Found</title>

So of course, as soon as I pushed an image:

172.20.2.1 - - [08/Oct/2020:13:33:17 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.19"
time="2020-10-08T13:33:18.008021748Z" level=error msg="retryingsink: error writing events: httpSink{http://harbor-core/service/notifications}: response status 404 Not Found unaccepted, retrying" 
time="2020-10-08T13:33:18.008050873Z" level=warning msg="httpSink{http://harbor-core/service/notifications} encountered too many errors, backing off" 

Thanks for your help !!
