### ISSUE TITLE
Harbor CLI

### ISSUE THREAD

**Issue by dbenduga** [goharbor/harbor#10911]
Getting below error.. Any solution for this...

[root@pun-harbor-03 ~]# harbor
Traceback (most recent call last):
  File "/usr/local/bin/harbor", line 6, in <module>
    from harborclient.shell import main
  File "/usr/local/lib/python3.6/site-packages/harborclient/shell.py", line 17, in <module>
    from harborclient import client
  File "/usr/local/lib/python3.6/site-packages/harborclient/client.py", line 8, in <module>
    from urlparse import urlparse
ModuleNotFoundError: No module named 'urlparse'
[root@pun-harbor-03 ~]#

**Comment by dbenduga** [comment]
I fixed above issue. Now getting below error 

[root@pun-harbor-03 ~]# harbor --insecure --os-baseurl http://pun-harbor-03.bmc.com --os-username dbenduga --os-project 3 info
password:
CommandError: Unable to authorize user 'dbenduga': {"reason": "Not Allowed", "message": "<html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx/1.16.1</center>
</body>
</html>
"}
[root@pun-harbor-03 ~]#

**Comment by wglambert** [comment]
For the `Unable to authorize user` if you're using https://github.com/int32bit/python-harborclient as your CLI client this issue might be relevant https://github.com/int32bit/python-harborclient/issues/17#issuecomment-503607370
>REMEMBER to add "/" in the end of your goharbor URL

Since issues with that CLI client aren't addressed in this repo https://github.com/goharbor/harbor/issues/7279#issuecomment-485672521

**Comment by dbenduga** [comment]
tried after adding "/" in the end of harbor URL but still getting same error.

[root@pun-harbor-03 ~]# harbor --insecure --os-baseurl https://pun-harbor-03.bmc.com/ --os-username dbenduga --os-project 3 info
password:
CommandError: Unable to authorize user 'dbenduga': {"reason": "Not Allowed", "message": "<html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx/1.16.1</center>
</body>
</html>
"}
[root@pun-harbor-03 ~]#
