### ISSUE TITLE
Strange behaviour when deleting an repo after GC

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#5078]
[Steps]:
1, Push one docker image into harbor.
2, Delete the repository.
3, Run GC with cmd: /usr/bin/registry garbage-collect /etc/registry/config.yml
4, Re-push the deleted images into harbor.

After that, I get the repo size with 0. And, I tried to delete it, UI shows as success and 200 from API, but actually the repo cannot be deleted.

[Root Cause]
After investigation, the root cause should be the GC bug of docker registry v2.6.2(cache invalidation). See issues:
https://github.com/docker/distribution/issues/2270
https://github.com/docker/distribution/issues/2094
https://github.com/docker/distribution/issues/2434
From the issue response, they could provide fix on 2.7, but no mention the schedule.

[Workaround]
Re-start registry and re-push the images.

[Issue on harbor]
For harbor, we eat the 404 error from docker registry, that's why it can get 200 from API when to delete the repository and cause the strange behaviour. https://github.com/vmware/harbor/blob/master/src/ui/api/repository.go#L295

[Log]
Jun  1 08:38:00 172.18.0.1 ui[1463]: 2018-06-01T15:38:00Z [ERROR] [repository.go:538]: failed to get v2 manifest of library1/tomcat:latest: 404 {"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown","detail":{"Name":"library1/tomcat","Revision":"sha256:8238fb3b0f8e15219399069a4aa78e88cbbce28834de5f1e55749067b82d14dc"}}]}

**Comment by clouderati** [comment]
@reasonerjt – I know we talked about this but can't recall if it was completely fixed in #5273. Thoughts?

**Comment by wy65701436** [comment]
from v1.6.1, harbor has upgraded to use redis as the cache of registry, and the GC job will delete all the keys from cache, which could workaround this issue. 

Close it as fix.

**Comment by lmdkfs** [comment]
i try to upgdate  to harbor v1.6.1. how can i view this gc job, i try to visite `api/system/gc`, the response is 404

**Comment by lmdkfs** [comment]
i also encountered this problem, so i upgrade harbor to 1.6.1, but this problem still  exists,  how can to use gc, thanks @wy65701436

**Comment by louyiping** [comment]
Also meet this problem with 1.6.0 version. Any idea?

**Comment by wy65701436** [comment]
The workaround on v1.6.1 is to clean the keys of the registry in redis, this could workaround the cache invalidation issue on registry v2.6.2

```
1, Go into the container -- goharbor/redis-photon,
2, Run 'redis-cli'
3, Run 'select 1'  (1 is the default DB index of registry)
4, Run 'flushdb'
5, User 'keys *' to validate all keys have been removed.

```
