### ISSUE TITLE
Support configuring "sslmode" when connecting to the database

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#5843]
The `sslmode` is hardcoded as `false` in Harbor, we need a way to allow the users to configure it, especially when using an external database.

**Comment by ywk253100** [comment]
Done

**Comment by KarstenSiemer** [comment]
that is not enough imo.
What about ssl settings like sslrootcert, sslcert and sslkey?
Why is everybody expected to not use self signed certificates?

**Comment by damyan** [comment]
> that is not enough imo. What about ssl settings like sslrootcert, sslcert and sslkey? Why is everybody expected to not use self signed certificates?

Anyone? Same problem here, with self-signed certifacates

**Comment by damyan** [comment]
Enabling SSL for external databases requires valid certificate data. I created a small PoC PR, which seems to tackle the issue pretty well, s. https://github.com/damyan/harbor-helm/pull/1.

Unfortunately, as mentioned in the PR, the notary deployments still fail due to fsGroup and secret mode not really working well with each other, s. https://github.com/kubernetes/kubernetes/issues/57923.

I ended up adding an init container, which sets the proper permissions (0600) on the client key. Adding an init container to the `notary` deployments is not (yet) exposed in the helm chart values, so I had to to some kustomize post rendering of the chart instead.

**Comment by mmurtha** [comment]
> > that is not enough imo. What about ssl settings like sslrootcert, sslcert and sslkey? Why is everybody expected to not use self signed certificates?
> 
> Anyone? Same problem here, with self-signed certificates.

Is there official support for this?  I need to configure an external DB connection with TLS cert auth.
